"""
Configuration for slide types and presentation structure
"""

# Slide types with their required components
SLIDE_TYPES = {
    "Welcome": {
        "components": ["title", "subtitle", "author"],
        "description": "Opening slide with presentation title, subtitle and author name",
        "include_in_prompt": True
    },
    "TableOfContents": {
        "components": ["sections"],
        "description": "Overview of presentation sections (up to 8 sections separated by commas, each optional)",
        "include_in_prompt": False  # Will be generated by generate_pptx.py instead
    },
    "Section": {
        "components": ["title"],
        "description": "Section divider slide with section title",
        "include_in_prompt": True
    },
    "ContentImage": {
        "components": ["title", "subtitle", "content", "image"],
        "description": "Content slide with text and an accompanying image (should be most of the slides)",
        "include_in_prompt": True
    },
    "Content": {
        "components": ["title", "content"],
        "description": "Standard content slide with bullet points",
        "include_in_prompt": True
    },
    "ImageFull": {
        "components": ["title", "image", "explanation"],
        "description": "Slide with dominant image and smaller text field for explanation",
        "include_in_prompt": True
    },
    "3Images": {
        "components": ["title", "image1", "image2", "image3", "subtitleimage1", "subtitleimage2", "subtitleimage3"],
        "description": "Slide with three images in grid layout, each with its own subtitle",
        "include_in_prompt": True
    },
    "ContentWithLogos": {
        "components": ["title", "content", "logo1", "logo2", "logo3"],
        "description": "Content slide with bullet points and up to three company/product logos",
        "include_in_prompt": True
    }
}

# Default presentation structure
PRESENTATION_STRUCTURE = {
    "order": ["Welcome", "TableOfContents", "Sections"],
    "max_sections": 8,
    "default_author": "Marko Milosevic",
    "auto_generate_toc": True  # Flag indicating that TableOfContents should be auto-generated
}

# Image format configuration for slide types
IMAGE_FORMATS = {
    "ContentImage": "1024x1536",
    "ImageFull": "1536x1024",
    "3Images": "1024x1024",
    "ContentWithLogos": "512x512",  # Smaller format for logos
    "default": "1024x1024"  # Default format for any other slide types with images
} 