"use client"

import { motion } from "framer-motion"
import type { Presentation } from "@/lib/types"

interface PptxStepProps {
  presentation: Presentation
}

export default function PptxStep({ presentation }: PptxStepProps) {
  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
        <h2 className="text-2xl font-bold mb-4 gradient-text">Presentation Ready</h2>
        <p className="text-gray-600 mb-6">
          Your presentation, "{presentation.name}", is structured and ready.
          You can export it as a PowerPoint file using the "Export PPTX" button in the header.
        </p>

        <div className="bg-white/90 backdrop-blur-sm rounded-xl shadow-md border border-gray-100 p-8 text-center">
          <div className="mb-8">
            <img src="/powerpoint-icon.png" alt="PowerPoint icon" className="mx-auto h-32 mb-4" />
            <h3 className="text-xl font-bold mb-2">{presentation.name}</h3>
            <p className="text-gray-500">
              {presentation.slides.length} slides • Created by {presentation.author}
            </p>
          </div>

          <div className="mt-8 p-4 bg-gray-50 rounded-lg text-sm text-gray-600">
            <p className="mb-2">
              <strong>Note:</strong> The exported presentation will include all slides and images you've created once generated by the backend.
            </p>
            <p>You can further customize the presentation in PowerPoint after downloading it.</p>
          </div>
        </div>
      </motion.div>
    </div>
  )
}
